### ISSUE TITLE
Progress on this?

### ISSUE THREAD

**Issue by bubach** [feryardiant/fpdf#1]
I noticed this repository a bit too late, since I've started my own refactoring of FPDF over at
https://github.com/bubach/PdfBuilder 

Maybe we could help each other out, or combine this in some way. Please let me know what you think of the parts I've gotten done so far.

**Comment by feryardiant** [comment]
Hi @bubach,

Sorry, I can't actively maintain this repo but still accepting bug related issue.

Great, that's awesome I'd love to contribute if I got free time.
